DROP TABLE Country CASCADE CONSTRAINTS;
DROP TABLE Province CASCADE CONSTRAINTS;
DROP TABLE City CASCADE CONSTRAINTS;
DROP TABLE Economy CASCADE CONSTRAINTS;
DROP TABLE Population CASCADE CONSTRAINTS;
DROP TABLE Politics CASCADE CONSTRAINTS;
DROP TABLE Language CASCADE CONSTRAINTS;
DROP TABLE Sublanguage CASCADE CONSTRAINTS;
DROP TABLE Religion CASCADE CONSTRAINTS;
DROP TABLE EthnicGroup CASCADE CONSTRAINTS;

DROP TABLE Countrypops CASCADE CONSTRAINTS;
DROP TABLE Provpops CASCADE CONSTRAINTS;
DROP TABLE Citypops CASCADE CONSTRAINTS;

DROP TABLE Countryothername CASCADE CONSTRAINTS;
DROP TABLE Provinceothername CASCADE CONSTRAINTS;
DROP TABLE Cityothername CASCADE CONSTRAINTS;

DROP TABLE Countrylocalname CASCADE CONSTRAINTS;
DROP TABLE Provincelocalname CASCADE CONSTRAINTS;
DROP TABLE Citylocalname CASCADE CONSTRAINTS;

DROP TABLE borders CASCADE CONSTRAINTS;

DROP TABLE Continent CASCADE CONSTRAINTS;
DROP TABLE encompasses CASCADE CONSTRAINTS;

DROP TABLE Organization CASCADE CONSTRAINTS;
DROP TABLE isMember CASCADE CONSTRAINTS;

DROP TABLE Mountain CASCADE CONSTRAINTS;
DROP TABLE Desert CASCADE CONSTRAINTS;
DROP TABLE Island CASCADE CONSTRAINTS;
DROP TABLE Lake CASCADE CONSTRAINTS;
DROP TABLE Sea CASCADE CONSTRAINTS;
DROP TABLE River CASCADE CONSTRAINTS;
DROP TABLE RiverThrough CASCADE CONSTRAINTS;

DROP TABLE geo_Mountain CASCADE CONSTRAINTS;
DROP TABLE geo_Desert CASCADE CONSTRAINTS;
DROP TABLE geo_Island CASCADE CONSTRAINTS;
DROP TABLE geo_River CASCADE CONSTRAINTS;
DROP TABLE geo_Sea CASCADE CONSTRAINTS;
DROP TABLE geo_Lake CASCADE CONSTRAINTS;
DROP TABLE geo_Source CASCADE CONSTRAINTS;
DROP TABLE geo_Estuary CASCADE CONSTRAINTS;

DROP TABLE mergesWith CASCADE CONSTRAINTS;
DROP TABLE located CASCADE CONSTRAINTS;
DROP TABLE locatedOn CASCADE CONSTRAINTS;
DROP TABLE islandIn CASCADE CONSTRAINTS;
DROP TABLE mountainOnIsland CASCADE CONSTRAINTS;
DROP TABLE riverOnIsland CASCADE CONSTRAINTS;
DROP TABLE lakeOnIsland CASCADE CONSTRAINTS;

DROP TABLE airport CASCADE CONSTRAINTS;


